"""Add processing status fields to audio_files

Revision ID: 11cfae3aff65
Revises: c2b235bed6aa
Create Date: 2025-11-21 04:43:27.445950

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '11cfae3aff65'
down_revision: Union[str, None] = 'c2b235bed6aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audio_files', sa.Column('processing_step', sa.String(length=50), nullable=True))
    op.add_column('audio_files', sa.Column('processing_progress', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('audio_files', sa.Column('processing_message', sa.String(length=200), nullable=True))
    op.add_column('audio_files', sa.Column('error_message', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('audio_files', 'error_message')
    op.drop_column('audio_files', 'processing_message')
    op.drop_column('audio_files', 'processing_progress')
    op.drop_column('audio_files', 'processing_step')
    # ### end Alembic commands ###
