"""add_multiturn_llm_and_role_based_tagging_fields

Revision ID: 28142f56d2d2
Revises: 9eb8318e9141
Create Date: 2025-11-13 03:16:31.418208

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28142f56d2d2'
down_revision: Union[str, None] = '9eb8318e9141'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('detected_names', sa.Column('context_before', sa.JSON(), nullable=True))
    op.add_column('detected_names', sa.Column('context_after', sa.JSON(), nullable=True))
    op.add_column('detected_names', sa.Column('llm_reasoning', sa.Text(), nullable=True))
    op.add_column('detected_names', sa.Column('is_consistent', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_detected_names_detected_name'), 'detected_names', ['detected_name'], unique=False)
    op.add_column('speaker_mappings', sa.Column('name_confidence', sa.Float(), nullable=True))
    op.add_column('speaker_mappings', sa.Column('name_mentions', sa.Integer(), nullable=False))
    op.add_column('speaker_mappings', sa.Column('suggested_role', sa.String(length=50), nullable=True))
    op.add_column('speaker_mappings', sa.Column('role_confidence', sa.Float(), nullable=True))
    op.add_column('speaker_mappings', sa.Column('conflict_detected', sa.Boolean(), nullable=False))
    op.add_column('speaker_mappings', sa.Column('needs_manual_review', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('speaker_mappings', 'needs_manual_review')
    op.drop_column('speaker_mappings', 'conflict_detected')
    op.drop_column('speaker_mappings', 'role_confidence')
    op.drop_column('speaker_mappings', 'suggested_role')
    op.drop_column('speaker_mappings', 'name_mentions')
    op.drop_column('speaker_mappings', 'name_confidence')
    op.drop_index(op.f('ix_detected_names_detected_name'), table_name='detected_names')
    op.drop_column('detected_names', 'is_consistent')
    op.drop_column('detected_names', 'llm_reasoning')
    op.drop_column('detected_names', 'context_after')
    op.drop_column('detected_names', 'context_before')
    # ### end Alembic commands ###
