"""add_speaker_profiles_table

Revision ID: 2eddc0de3d29
Revises: 89466e87344b
Create Date: 2025-11-30 05:44:22.718641

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '2eddc0de3d29'
down_revision: Union[str, None] = '89466e87344b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('speaker_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('speaker_name', sa.String(length=100), nullable=False),
    sa.Column('voice_embedding', sa.JSON(), nullable=True),
    sa.Column('text_embedding', sa.JSON(), nullable=True),
    sa.Column('sample_texts', sa.JSON(), nullable=True),
    sa.Column('source_audio_file_id', sa.Integer(), nullable=True),
    sa.Column('confidence_score', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['source_audio_file_id'], ['audio_files.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_speaker_profiles_id'), 'speaker_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_speaker_profiles_user_id'), 'speaker_profiles', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_speaker_profiles_user_id'), table_name='speaker_profiles')
    op.drop_index(op.f('ix_speaker_profiles_id'), table_name='speaker_profiles')
    op.drop_table('speaker_profiles')
    # ### end Alembic commands ###
