"""Initial migration

Revision ID: 9eb8318e9141
Revises: 
Create Date: 2025-11-10 06:39:20.218522

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9eb8318e9141'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('oauth_provider', sa.Enum('GOOGLE', 'KAKAO', 'GITHUB', name='oauthprovider'), nullable=True),
    sa.Column('oauth_id', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email', 'oauth_provider', name='uq_user_email_oauth'),
    sa.UniqueConstraint('oauth_provider', 'oauth_id', name='uq_user_oauth_provider_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('audio_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=False),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('mimetype', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('UPLOADED', 'PROCESSING', 'COMPLETED', 'FAILED', name='filestatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audio_files_id'), 'audio_files', ['id'], unique=False)
    op.create_index(op.f('ix_audio_files_status'), 'audio_files', ['status'], unique=False)
    op.create_index(op.f('ix_audio_files_user_id'), 'audio_files', ['user_id'], unique=False)
    op.create_table('detected_names',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('audio_file_id', sa.Integer(), nullable=False),
    sa.Column('detected_name', sa.String(length=100), nullable=False),
    sa.Column('speaker_label', sa.String(length=50), nullable=False),
    sa.Column('time_detected', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('similarity_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['audio_file_id'], ['audio_files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_detected_names_audio_file_id'), 'detected_names', ['audio_file_id'], unique=False)
    op.create_index(op.f('ix_detected_names_id'), 'detected_names', ['id'], unique=False)
    op.create_table('diarization_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('audio_file_id', sa.Integer(), nullable=False),
    sa.Column('speaker_label', sa.String(length=50), nullable=False),
    sa.Column('start_time', sa.Float(), nullable=False),
    sa.Column('end_time', sa.Float(), nullable=False),
    sa.Column('embedding', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['audio_file_id'], ['audio_files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_diar_audio_speaker', 'diarization_results', ['audio_file_id', 'speaker_label'], unique=False)
    op.create_index(op.f('ix_diarization_results_audio_file_id'), 'diarization_results', ['audio_file_id'], unique=False)
    op.create_index(op.f('ix_diarization_results_id'), 'diarization_results', ['id'], unique=False)
    op.create_table('final_transcripts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('audio_file_id', sa.Integer(), nullable=False),
    sa.Column('segment_index', sa.Integer(), nullable=False),
    sa.Column('speaker_name', sa.String(length=100), nullable=False),
    sa.Column('start_time', sa.Float(), nullable=False),
    sa.Column('end_time', sa.Float(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['audio_file_id'], ['audio_files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_final_transcripts_audio_file_id'), 'final_transcripts', ['audio_file_id'], unique=False)
    op.create_index(op.f('ix_final_transcripts_id'), 'final_transcripts', ['id'], unique=False)
    op.create_index('ix_transcript_audio_segment', 'final_transcripts', ['audio_file_id', 'segment_index'], unique=False)
    op.create_table('preprocessing_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('audio_file_id', sa.Integer(), nullable=False),
    sa.Column('stt_input_path', sa.String(length=500), nullable=False),
    sa.Column('diar_input_path', sa.String(length=500), nullable=False),
    sa.Column('processing_time', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['audio_file_id'], ['audio_files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_preprocessing_results_audio_file_id'), 'preprocessing_results', ['audio_file_id'], unique=True)
    op.create_index(op.f('ix_preprocessing_results_id'), 'preprocessing_results', ['id'], unique=False)
    op.create_table('speaker_mappings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('audio_file_id', sa.Integer(), nullable=False),
    sa.Column('speaker_label', sa.String(length=50), nullable=False),
    sa.Column('suggested_name', sa.String(length=100), nullable=True),
    sa.Column('final_name', sa.String(length=100), nullable=False),
    sa.Column('is_modified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['audio_file_id'], ['audio_files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('audio_file_id', 'speaker_label', name='uq_speaker_mapping_audio_speaker')
    )
    op.create_index(op.f('ix_speaker_mappings_audio_file_id'), 'speaker_mappings', ['audio_file_id'], unique=False)
    op.create_index(op.f('ix_speaker_mappings_id'), 'speaker_mappings', ['id'], unique=False)
    op.create_table('stt_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('audio_file_id', sa.Integer(), nullable=False),
    sa.Column('word_index', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=100), nullable=False),
    sa.Column('start_time', sa.Float(), nullable=False),
    sa.Column('end_time', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['audio_file_id'], ['audio_files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_stt_audio_word', 'stt_results', ['audio_file_id', 'word_index'], unique=False)
    op.create_index(op.f('ix_stt_results_audio_file_id'), 'stt_results', ['audio_file_id'], unique=False)
    op.create_index(op.f('ix_stt_results_id'), 'stt_results', ['id'], unique=False)
    op.create_table('summaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('audio_file_id', sa.Integer(), nullable=False),
    sa.Column('summary_type', sa.Enum('SUMMARY', 'SUBTITLE', name='summarytype'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['audio_file_id'], ['audio_files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_summaries_audio_file_id'), 'summaries', ['audio_file_id'], unique=False)
    op.create_index(op.f('ix_summaries_id'), 'summaries', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_summaries_id'), table_name='summaries')
    op.drop_index(op.f('ix_summaries_audio_file_id'), table_name='summaries')
    op.drop_table('summaries')
    op.drop_index(op.f('ix_stt_results_id'), table_name='stt_results')
    op.drop_index(op.f('ix_stt_results_audio_file_id'), table_name='stt_results')
    op.drop_index('ix_stt_audio_word', table_name='stt_results')
    op.drop_table('stt_results')
    op.drop_index(op.f('ix_speaker_mappings_id'), table_name='speaker_mappings')
    op.drop_index(op.f('ix_speaker_mappings_audio_file_id'), table_name='speaker_mappings')
    op.drop_table('speaker_mappings')
    op.drop_index(op.f('ix_preprocessing_results_id'), table_name='preprocessing_results')
    op.drop_index(op.f('ix_preprocessing_results_audio_file_id'), table_name='preprocessing_results')
    op.drop_table('preprocessing_results')
    op.drop_index('ix_transcript_audio_segment', table_name='final_transcripts')
    op.drop_index(op.f('ix_final_transcripts_id'), table_name='final_transcripts')
    op.drop_index(op.f('ix_final_transcripts_audio_file_id'), table_name='final_transcripts')
    op.drop_table('final_transcripts')
    op.drop_index(op.f('ix_diarization_results_id'), table_name='diarization_results')
    op.drop_index(op.f('ix_diarization_results_audio_file_id'), table_name='diarization_results')
    op.drop_index('ix_diar_audio_speaker', table_name='diarization_results')
    op.drop_table('diarization_results')
    op.drop_index(op.f('ix_detected_names_id'), table_name='detected_names')
    op.drop_index(op.f('ix_detected_names_audio_file_id'), table_name='detected_names')
    op.drop_table('detected_names')
    op.drop_index(op.f('ix_audio_files_user_id'), table_name='audio_files')
    op.drop_index(op.f('ix_audio_files_status'), table_name='audio_files')
    op.drop_index(op.f('ix_audio_files_id'), table_name='audio_files')
    op.drop_table('audio_files')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
