"""Add meeting_efficiency_analysis table

Revision ID: b15f90cfcefa
Revises: add_rag_status_fields
Create Date: 2025-11-26 02:11:24.964190

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b15f90cfcefa'
down_revision: Union[str, None] = 'add_rag_status_fields'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meeting_efficiency_analysis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('audio_file_id', sa.Integer(), nullable=False),
    sa.Column('entropy_values', sa.JSON(), nullable=True),
    sa.Column('entropy_avg', sa.Float(), nullable=True),
    sa.Column('entropy_std', sa.Float(), nullable=True),
    sa.Column('speaker_metrics', sa.JSON(), nullable=False),
    sa.Column('total_speakers', sa.Integer(), nullable=False),
    sa.Column('total_turns', sa.Integer(), nullable=False),
    sa.Column('total_sentences', sa.Integer(), nullable=False),
    sa.Column('analysis_version', sa.String(length=20), nullable=False, server_default='1.0'),
    sa.Column('analyzed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['audio_file_id'], ['audio_files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meeting_efficiency_analysis_audio_file_id'), 'meeting_efficiency_analysis', ['audio_file_id'], unique=True)
    op.create_index(op.f('ix_meeting_efficiency_analysis_id'), 'meeting_efficiency_analysis', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_meeting_efficiency_analysis_id'), table_name='meeting_efficiency_analysis')
    op.drop_index(op.f('ix_meeting_efficiency_analysis_audio_file_id'), table_name='meeting_efficiency_analysis')
    op.drop_table('meeting_efficiency_analysis')
    # ### end Alembic commands ###
